path: C:\Users\LX\Documents\Código Steampact\RaspberrySet\data
train: images\train
val: images\train
  
#Class names

names:
  0: Buds
  1: Flowers
  2: Unripe Berries
  3: Ripe Berries
  4: Damaged Buds
